### ISSUE TITLE
Create replica tab for enterprise geodatabases

### ISSUE THREAD

**Issue by tom-montgomery** [AlexArcPy/registrant#3]
Managing replicas is not very easy with the ArcGIS GUI As you cannot copy the replica data list (which tables/feature classes are included in replica) easily to manage the replica data. 
It is possible with SQL Server Management Studio, but it would be nice if it were included in the registrant HTML output.
Replica tab could include:
replica names
replica data
replica history

**Comment by AlexArcPy** [comment]
@tom-montgomery , excellent idea! Let me see if this information is exposed via `arcpy`. I'll get back to this issue this week.

**Comment by AlexArcPy** [comment]
Hey @tom-montgomery , `arcpy` does expose quite some information about the replicas, so I am adding the `Replicas` section to the report. However, to get the list of the datasets I'd need to export the geodatabase schema into an XML first and then parse it. I am working on this.

What do you think would make most sense - having the information about the datasets participating in the replica for each replica as a comma separated list (`Datasets` column)

![fig1](https://user-images.githubusercontent.com/7373268/32217460-5aa0f026-be28-11e7-9415-d6e76d527afd.png)

or as a property for each individual table/fc (`Replica` column)

![fig2](https://user-images.githubusercontent.com/7373268/32217487-7018a6b0-be28-11e7-9d1d-07f0106700c9.png)

?

**Comment by tom-montgomery** [comment]
Awesome thanks for looking considering it. 
I would prefer to have the replica datasets as an entire list like in your first screenshot. The main reason is if I need to add a feature class or table to an existing replica it requires re-creating the entire replica as you cannot simply add a single new data. So, yes the concise list would be best from the enterprise management perspective. 
This may be out of scope of this project but really what would be ideal would be auto creation of an MXD of the existing replica datasets for easy re-creation.

**Comment by AlexArcPy** [comment]
@tom-montgomery , no worries! Thanks for the clarification, this makes perfect sense. I am able to parse the datasets within the replica in the database, I've decided to make a nice list of datasets instead of the comma separated text.

I've also decided to include both the dataset name and the target name. For example, when reading the datasets in the replica inside a file geodatabase that is a one-way replica (of an SDE geodatabase), then it would be "cities -> DbName.DBO.Cities". This is how it looks.

For SDE gdb:

![fig1](https://user-images.githubusercontent.com/7373268/32335632-921d02c6-bfed-11e7-89fc-580fc342efd2.png)

For file gdb:

![filegdb](https://user-images.githubusercontent.com/7373268/32335779-f3438e30-bfed-11e7-836e-e3cfd967dc40.png)

As I am anyways have access to the XML of the replica, maybe there is something else you would like to be reported? I have added the `Creation date` as you can see. You can explore the information about replicas if you export the replicas into an schema XML file using the GP tool http://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/export-replica-schema.htm.

When this is set, I am ready to push so you could start using the latest version :)

**Comment by AlexArcPy** [comment]
@tom-montgomery , regarding your request 

> what would be ideal would be auto creation of an MXD of the existing replica datasets for easy re-creation.

I would really like focusing on reporting in this particular package, so this is not something I'd consider adding. However, by all means, please ask a question on https://gis.stackexchange.com/ and me or someone else would be able to help you writing a Python script that would re-create an .mxd file with the datasets listed in an existing replica, doesn't sound hard at all, can be written under 20-30 lines of Python.

**Comment by tom-montgomery** [comment]
Awesome! I look forward to the implementation, thanks.

**Comment by AlexArcPy** [comment]
Just published the v0.2, feel free to grab and install. Please let me know anything you think could make reporting replicas (or anything else in geodatabase) more useful to you!

**Comment by AlexArcPy** [comment]
@tom-montgomery , just published the v0.3 with the reporting of SDE versions added. Maybe also something useful to you. Looks like this:

![versions_sde](https://user-images.githubusercontent.com/7373268/32372208-2cf54c44-c094-11e7-8a32-b1b10da67dd8.png)

**Comment by tom-montgomery** [comment]
@AlexArcPy  Versions will be very helpful as well. Im going to schedule this for all of our geodatabases (have a couple dozen) as a quick administrative reference. v0.3 looks great!
