### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Reporter'

### ISSUE THREAD

**Issue by wagisdev** [AlexArcPy/registrant#5]
New installation here that ran into some issues.  Took a look at past issues and couldn't find any point of commonality.  Setup is as follows:  ArcGIS 10.5.1, Enterprise GDB (MS-SQL), and running Python 2.7.13.

Error being reported is as follows:  
Traceback (most recent call last):
  File "C:\Python27\registrant-master\run.py", line 2, in <module>
    reporter = registrant.Reporter(r"Database Connections\Connection to Carta on SQL2016GTS.sde", r"C:\GIS\Carta-GTS")
AttributeError: 'module' object has no attribute 'Reporter'

Call is coming from python script with contents:
import registrant
reporter = registrant.Reporter(r"Database Connections\Connection to Carta on SQL2016GTS.sde", r"C:\GIS\Carta-GTS")
reporter.gdb2html()
print(reporter.report_file_path)

Any thoughts?

**Comment by AlexArcPy** [comment]
Hey thanks for posting this. Always fun to see someone trying to run the programs you write ;) I am travelling at the moment, but please let me take a look at this when I have access to a machine with `arcpy`. I'll post later.

**Comment by wagisdev** [comment]
Not a problem.  I started looking at your solution as a solution in house over here because it would cut down on pretty much how every weird question that gets asked of me on a daily basis.  LOL.

To the point, of yeah, I totally am with you on that.  Safe travels and I appreciate you looking into it when you have a moment.  Thanks so much!

**Comment by AlexArcPy** [comment]
Hi there. Sorry that it took me so long. I've tried installing `registrant` on a fresh machine with 10.6 installed. No problem at all. Let's try to nail down the problem with your environment.

1. List versions all the packages `registrant` depends upon.
2. Are you able to import `arcpy` and use Python in ArcGIS no problem?
3. Can you inspect the `registrant` module after it has been imported - run `dir(registrant)` - maybe there is something wrong with it.

Can you isolate the problem by trying to install `registrant` on a sandbox with fresh installation of ArcGIS Desktop? I guess the step `3` would be most interesting though.

**Comment by wagisdev** [comment]
Hi there to you too.  Yeah, I've been tied up with some other projects myself and have finally circled around to your response.  I'll give it another shot and see what comes of it.  Thanks for the advice on where to start looking.  More to come.

**Comment by AlkalineCandy79** [comment]
Okay...from a fresh install....

Here is what I am getting when I go through the setup process:

`E:\registrant-master>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to registrant.egg-info\requires.txt
writing registrant.egg-info\PKG-INFO
writing top-level names to registrant.egg-info\top_level.txt
writing dependency_links to registrant.egg-info\dependency_links.txt
reading manifest file 'registrant.egg-info\SOURCES.txt'
writing manifest file 'registrant.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build\bdist.win32\egg
creating build\bdist.win32\egg\registrant
creating build\bdist.win32\egg\registrant\app
creating build\bdist.win32\egg\registrant\app\css
copying build\lib\registrant\app\css\bootstrap.min.css -> build\bdist.win32\egg\registrant\app\css
copying build\lib\registrant\app\css\buttons.dataTables.min.css -> build\bdist.win32\egg\registrant\app\css
copying build\lib\registrant\app\css\colReorder.dataTables.min.css -> build\bdist.win32\egg\registrant\app\css
copying build\lib\registrant\app\css\dashboard.css -> build\bdist.win32\egg\registrant\app\css
copying build\lib\registrant\app\css\dataTables.bootstrap.min.css -> build\bdist.win32\egg\registrant\app\css
copying build\lib\registrant\app\css\ie10-viewport-bug-workaround.css -> build\bdist.win32\egg\registrant\app\css
copying build\lib\registrant\app\css\select.dataTables.min.css -> build\bdist.win32\egg\registrant\app\css
creating build\bdist.win32\egg\registrant\app\fonts
copying build\lib\registrant\app\fonts\glyphicons-halflings-regular.eot -> build\bdist.win32\egg\registrant\app\fonts
copying build\lib\registrant\app\fonts\glyphicons-halflings-regular.svg -> build\bdist.win32\egg\registrant\app\fonts
copying build\lib\registrant\app\fonts\glyphicons-halflings-regular.ttf -> build\bdist.win32\egg\registrant\app\fonts
copying build\lib\registrant\app\fonts\glyphicons-halflings-regular.woff -> build\bdist.win32\egg\registrant\app\fonts
copying build\lib\registrant\app\fonts\glyphicons-halflings-regular.woff2 -> build\bdist.win32\egg\registrant\app\fonts
creating build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\js\bootstrap.min.js -> build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\js\buttons.print.min.js -> build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\js\dataTables.bootstrap.min.js -> build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\js\dataTables.buttons.min.js -> build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\js\dataTables.colReorder.min.js -> build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\js\dataTables.select.min.js -> build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\js\holder.min.js -> build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\js\ie-emulation-modes-warning.js -> build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\js\ie10-viewport-bug-workaround.js -> build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\js\jquery.dataTables.min.js -> build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\js\jquery.min.js -> build\bdist.win32\egg\registrant\app\js
copying build\lib\registrant\app\__init__.py -> build\bdist.win32\egg\registrant\app
creating build\bdist.win32\egg\registrant\html-template
copying build\lib\registrant\html-template\template.html -> build\bdist.win32\egg\registrant\html-template
copying build\lib\registrant\html-template\__init__.py -> build\bdist.win32\egg\registrant\html-template
copying build\lib\registrant\_build_html.py -> build\bdist.win32\egg\registrant
copying build\lib\registrant\_config.py -> build\bdist.win32\egg\registrant
copying build\lib\registrant\_data_objects.py -> build\bdist.win32\egg\registrant
copying build\lib\registrant\_geodatabase.py -> build\bdist.win32\egg\registrant
copying build\lib\registrant\_reporter.py -> build\bdist.win32\egg\registrant
copying build\lib\registrant\_util_mappings.py -> build\bdist.win32\egg\registrant
copying build\lib\registrant\__init__.py -> build\bdist.win32\egg\registrant
byte-compiling build\bdist.win32\egg\registrant\app\__init__.py to __init__.pyc
byte-compiling build\bdist.win32\egg\registrant\html-template\__init__.py to __init__.pyc
byte-compiling build\bdist.win32\egg\registrant\_build_html.py to _build_html.pyc
byte-compiling build\bdist.win32\egg\registrant\_config.py to _config.pyc
byte-compiling build\bdist.win32\egg\registrant\_data_objects.py to _data_objects.pyc
byte-compiling build\bdist.win32\egg\registrant\_geodatabase.py to _geodatabase.pyc
byte-compiling build\bdist.win32\egg\registrant\_reporter.py to _reporter.pyc
byte-compiling build\bdist.win32\egg\registrant\_util_mappings.py to _util_mappings.pyc
byte-compiling build\bdist.win32\egg\registrant\__init__.py to __init__.pyc
creating build\bdist.win32\egg\EGG-INFO
copying registrant.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying registrant.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying registrant.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying registrant.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying registrant.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
registrant._config: module references __file__
creating 'dist\registrant-0.7-py2.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing registrant-0.7-py2.7.egg
removing 'c:\python27\arcgis10.6\lib\site-packages\registrant-0.7-py2.7.egg' (and everything under it)
creating c:\python27\arcgis10.6\lib\site-packages\registrant-0.7-py2.7.egg
Extracting registrant-0.7-py2.7.egg to c:\python27\arcgis10.6\lib\site-packages
registrant 0.7 is already the active version in easy-install.pth

Installed c:\python27\arcgis10.6\lib\site-packages\registrant-0.7-py2.7.egg
Processing dependencies for registrant==0.7
Searching for pandas>=0.20.1
Reading https://pypi.python.org/simple/pandas/
Downloading https://files.pythonhosted.org/packages/36/de/76ea12678b05be72769da2b648b778bae2eeaddea1989b2abfb800ec4d01/pandas-0.24.0rc1.tar.gz#sha256=5ee45ee9bc2676ed603595a7f5ef9aa43fbc78af19d671d429e090df7e63fedf
Best match: pandas 0.24.0rc1
Processing pandas-0.24.0rc1.tar.gz
Writing c:\users\john.spence\appdata\local\temp\easy_install-vulxkc\pandas-0.24.0rc1\setup.cfg
Running pandas-0.24.0rc1\setup.py -q bdist_egg --dist-dir c:\users\john.spence\appdata\local\temp\easy_install-vulxkc\pandas-0.24.0rc1\egg-dist-tmp-xquloo
c:\users\john.spence\appdata\local\temp\easy_install-vulxkc\pandas-0.24.0rc1\temp\easy_install-9lirrj\numpy-1.16.0\setup.py:390: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
error: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\john.spence\\appdata\\local\\temp\\easy_install-vulxkc\\pandas-0.24.0rc1\\temp\\easy_install-9lirrj\\numpy-1.16.0\\numpy\\core\\setup.py'`

**Comment by AlkalineCandy79** [comment]
Pip is showing the following:  

C:\>pip check
registrant 0.7 has requirement pandas>=0.20.1, but you have pandas 0.18.1.
beautifulsoup4 4.7.1 requires soupsieve, which is not installed.
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by wagisdev** [comment]
OMG...Gotta love the difference between 32 and 64 bit installations with ESRI.  That initially was causing me some grief considering when you work outside of ESRI in python depending on the version you installed, you may have the 64 bit vs 32 bit running.

Okay, so here are some logs from installation and run attempts.  I can import arcpy without any issue.  With I go to run it, the error you see in pyscripter shows up.  General messages indicate there is a missing tuple object that has no type.  

[install_log.txt](https://github.com/AlexArcPy/registrant/files/2780751/install_log.txt)
![arc_catalog_run](https://user-images.githubusercontent.com/35645358/51503423-ca1df300-1d8f-11e9-99cc-0dd19a6a1c5d.PNG)
![pyscripter_error_logdetail](https://user-images.githubusercontent.com/35645358/51503445-ecb00c00-1d8f-11e9-8401-744c1aac9c26.PNG)
![missing_tuple](https://user-images.githubusercontent.com/35645358/51503505-41538700-1d90-11e9-9c2c-9d38244e3ed8.PNG)

Let me know what you think.  It's a puzzler for sure for me.

**Comment by wagisdev** [comment]
Oh!  BTW, just wanted to say thank you for your insights and help to get this going.  I am eager to see what your application pops out for all 28 of my spatial databases.  Kid you not.

**Comment by AlexArcPy** [comment]
No worries at all. I've seen this behaviour before. It is most likely because there are existing installations of pandas and numpy that are shipped along with arcpy installation. Could you please take a look inside the site-packages folder `C:\Python27\arcgis\Lib\site-packages` and see if you have multiple pandas versions folders? Delete the one of earlier version and restart your PyScripter. Try importing numpy and importing pandas. If this does not help, run `pip uninstall pandas` (or just delete the pandas folder altogether) and then do fresh `pip install pandas==0.23` to install it. pandas depend on numpy and some discrepancies in versions may cause pandas to choke. Let me know how it goes.

**Comment by wagisdev** [comment]
Sounds good.  I'll give it a shot sometime in the next day or two (at most).

**Comment by wagisdev** [comment]
@AlexArcPy I was able to get it to work.  Being a Python noob, I was stepping on my own feet.

So...here is where I am at.  I can get via the IDE setup to run and import registrant, etc.  I can get everything to run and create an output so pandas and BS4 is working correctly.  

- 2 issues.

1. setup.py install results in:  "error: package directory 'registrant' does not exist"
Example of run called via cmd:  C:\Python27\ArcGIS10.6>python C:\Users\John\Downloads\registrant-master\setup.py install

2.  When I backdoor everything and run setup.py via the IDE, I can get it to pop up and run successfully, but the output is creates is missing all the table information, content, etc.  The template/shell is there and populated as you show in your images, just nothing about the database is there.

The database I am trying to connect to is a Enterprise database (SDE).

Code is as follows:  
import registrant
reporter = registrant.Reporter(r"C:\Users\John\AppData\Roaming\ESRI\Desktop10.6\ArcCatalog\Connection.sde", r"C:\Users\John\Downloads\GIS")
reporter.gdb2html()
print(reporter.report_file_path)

Might be due to how I backdoored the failed install.

My previous errors were all due to my not realizing I had the 64-bit version installed and there were 2 different Python directories I was working from.  Sorry about that.

**Comment by wagisdev** [comment]
@AlexArcPy , I also tried to pip the install via pip install C:\Users\John\Downloads\registrant-master, but it errors out when it hits here:

![image](https://user-images.githubusercontent.com/35645358/57202126-83c35d00-6f56-11e9-99c1-48f4144f5005.png)

**Comment by wagisdev** [comment]
Went looking for what was calling numpy and couldn't find it for the likes of me.  FYI, all this was done in a sandbox (virtual machine) running ArcGIS 10.6.1 without the 64bit processing.  I am fixing to install Pro here in a minute and give it a shot there.

**Comment by wagisdev** [comment]
@AlexArcPy ...completely ignore me.  I switched over to Pro and being a bit more familiar w/ the configuration challenges there with python, was able to easily install and run the application.  Pretty darn snazzy and did exactly what I needed.  Thank you!

**Comment by AlexArcPy** [comment]
Ah glad it worked out well, sorry it took some efforts from you to get it up and running. Enjoy it and please do let me know if you think I could make this tool more helpful / suitable for your needs.
